name: E2E on Chrome
on: [push]
jobs:
  cypress-run:
    runs-on: windows-latest
    # let's make sure our tests pass on Chrome browser
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          build: npm run build
          start: npm start
          wait-on: http://localhost:3030
